apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: marketplace-app
spec:
  project: default
  source:
    repoURL: https://github.com/your-username/infra-automation-3d-marketplace
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true