apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketplace-deployment
  labels:
    app: marketplace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: marketplace
  template:
    metadata:
      labels:
        app: marketplace
    spec:
      containers:
      - name: marketplace-container
        image: 3d-marketplace:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: ENV
          value: production